export const AUTH_ACCESSTOKEN_REQUEST = "AUTH_ACCESSTOKEN_REQUEST";
export const AUTH_ACCESSTOKEN_SUCCESS = "AUTH_ACCESSTOKEN_SUCCESS";
export const AUTH_ACCESSTOKEN_FAIL = "AUTH_ACCESSTOKEN_FAIL";
export const AUTH_ACCESSTOKEN_DELETE = "AUTH_ACCESSTOKEN_DELETE";
export const AUTH_ACCESSTOKEN_INTERVAL = "AUTH_ACCESSTOKEN_INTERVAL";
